apiVersion: apps/v1
kind: Deployment
metadata:
  name: veriphrase-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veriphrase-backend
  template:
    metadata:
      labels:
        app: veriphrase-backend
    spec:
      containers:
      - name: veriphrase-backend
        image: myACR.azurecr.io/veriphrase-backend:v1
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: veriphrase-backend
spec:
  selector:
    app: veriphrase-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
