apiVersion: apps/v1
kind: Deployment
metadata:
  name: veriphrase-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veriphrase-frontend
  template:
    metadata:
      labels:
        app: veriphrase-frontend
    spec:
      containers:
      - name: veriphrase-frontend
        image: myACR.azurecr.io/veriphrase-frontend:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: veriphrase-frontend
spec:
  selector:
    app: veriphrase-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
